# frozen_string_literal: true

source "https://rubygems.org"

gem "allure-cucumber"
gem "appium_lib"
gem 'cucumber', '5.2'
gem "rspec"
gem "pry"
gem "appium_console"
gem 'selenium-webdriver', '~> 4.0'
gem "ffaker"
gem 'appium_lib_core', '~> 5.0'
